### ISSUE TITLE
update response list

### ISSUE THREAD

**Issue by stefaanternier** [WELTEN/dojo-ibl#12]
when I click "save & continue", the response list is not updated.

I think I would not implement "save & close". As a user, you want as feedback, to see your response...

so ... drop "save en close" en replace "save en continue" bye "submit".

Remove cancel...

**Comment by Titogelo** [comment]
#8

**Comment by stefaanternier** [comment]
The issues here are different from #8. I would maintain rather small tickets, so that you don't have to invest to much for each ticket.

**Comment by Titogelo** [comment]
Okay. yes it will be better.
