### ISSUE TITLE
The tree shows the inquiries under the About DojoIBL root

### ISSUE THREAD

**Issue by marcuspecht** [WELTEN/dojo-ibl#144]
wrong sorting in tree on left ...
<img width="247" alt="screen shot 2016-07-08 at 16 10 21" src="https://cloud.githubusercontent.com/assets/866385/16693144/1f3dab46-4534-11e6-8daa-5ac7723c8dec.png">

**Comment by marcuspecht** [comment]
why does it not show the about dojoibl inquiry under the inquiries root?

**Comment by Titogelo** [comment]
Good one. yes it makes sense to have it under inquiries.
