### ISSUE TITLE
upload file goes wrong on SAFARI and Chrome OS X

### ISSUE THREAD

**Issue by marcuspecht** [WELTEN/dojo-ibl#147]
it show the progress bar and then does nothing

**Comment by marcuspecht** [comment]
BTW it also does not work on Chrome. On chrome even the progress bar does not start ;-(

**Comment by Titogelo** [comment]
Thanks for the feedback. I dont know whats going on with the upload. For the moment, I would discard a browser related issue because for me it works even on smartphones and tablets. I am going to try with somelse's laptop to check if something different happens. I'll keep you inform here about it.

**Comment by Titogelo** [comment]
I have tried in other laptops, several browsers and it works. It takes a bit of time to upload but you can see it with the progress bar.

**Comment by Titogelo** [comment]
All the tests I have done it works, so I am going to close. If it does not work for you we can open it again and add it to next milestone.
