### ISSUE TITLE
messages on the chat just appear after reload

### ISSUE THREAD

**Issue by marcuspecht** [WELTEN/dojo-ibl#161]
I type something and it is not posted immediately

**Comment by Titogelo** [comment]
There a quota limit for the channels created (for the google channel api) the limit is set in 100. I need to check how to optimise the use of these channels.

**Comment by Titogelo** [comment]
**Context**: DojoIBL messaging works with Google Cloud Messaging (GCM). GCM uses Google Channels API to enable push notifications which is essential for the DojoIBL messaging to work. And these channels API generate a token to establish the connection. 

**Problem**: There is a limit of 100 channels API (tokens) per day. I was creating those channels in an inefficient way. Channels were created on every page load.

<img width="1154" alt="screen shot 2016-08-19 at 12 43 28" src="https://cloud.githubusercontent.com/assets/1598632/17807413/a589ade8-660a-11e6-818a-e3156ce60127.png">

**Solution**: Following the GCM tutorial, there should be a token per each user. So, we have optimised the management of these channels (tokens). Now, a new channel (token) is created whenever a new user connected. The token of the channel is stored in the cache and we reuse whenever the user needs it again. 
Whenever the token get to the expiration date the error callback function return an error and we prompt a message on the screen. The users have to reload the page and automatically a new token will be created.

**Comment by stefaanternier** [comment]
btw... the amount of channels is raised to 100k I think when you upgrade to
a paid plan.

Best,
Stefaan

On 19 August 2016 at 13:51, Angel Suarez Fernandez <notifications@github.com
