### ISSUE TITLE
Create an inquiry (use a template)

### ISSUE THREAD

**Issue by stefaanternier** [WELTEN/dojo-ibl#204]
At creation time, provide two options 
1.  Empty inquiry
2. weSPOT IBL model (default) -> initializes the inquiry with ibl phases and some demo activities?

**Comment by Titogelo** [comment]
#202

**Comment by Titogelo** [comment]
**Problem** Indeed there is a problem creating new inquiries. It is hard for users to come up with good inquiry structures and its content.

**Proposal** JSON file with pre-defined structures to select from them. At the same time, to create a new inquiry we add a screen before to select template and use it is selected we go to the existing view.

**Example of inquiry structure template**
I could add different inquiry structures from the Review of Marcus Pedaste and add to our catalogue for inquiries. 
https://gist.github.com/Titogelo/e8f82b332dd29f77a3c2a75834852a6b
