### ISSUE TITLE
Where do items go after they are added to TODO phase?

### ISSUE THREAD

**Issue by DanielPD** [WELTEN/dojo-ibl#230]
I made a new project "2SSXL" with a problem statement TODO at the start. I was adding items, but could't find how to retrieve the items I had added.

**Comment by Titogelo** [comment]
I joined your inquiry and it seems that everything is there.

**Comment by Titogelo** [comment]
We can use the chat if you still cannot see anything...

**Comment by DanielPD** [comment]
![screen shot 2016-11-08 at 14 00 32](https://cloud.githubusercontent.com/assets/6606498/20100042/cab6e87e-a5bb-11e6-918b-1a7550c452bb.png)

**Comment by Titogelo** [comment]
I think we can close this one!
