### ISSUE TITLE
Creating inquiries - create a role

### ISSUE THREAD

**Issue by stefaanternier** [WELTEN/dojo-ibl#45]
I'm asked to create a role, but I can't create one.

**Comment by Titogelo** [comment]
I need to know the way to add roles to a Game. I researched about and I have found two ways:

1) Using http://localhost:8888/rest/myGames sending the entire Game object. Used in author.html
2) Using config/gameId/{gameIdentifier}/role [POST] from the API. 

Which one is the correct one? @stefaanternier

**Comment by Titogelo** [comment]
This is solved in the new version of DojoIBL
