### ISSUE TITLE
join versus access inquiry

### ISSUE THREAD

**Issue by fleurprinsen** [WELTEN/dojo-ibl#78]
the button join inquiry is basically to find an inquiry. Otherwise you can go in through access inquiry, but right now the right way to go in is unclear (should I join or access?). Maybe button ' join inquiry'  should say 'find and join your inquiry'?

**Comment by Titogelo** [comment]
these two are related https://github.com/WELTEN/dojo-ibl/issues/77

I would mask the button when I am already in a inquiry. I will think about the title but to button that's currently named as "Join Inquiry". Your suggestion "Find & Join inquiry" could be an option.
