### ISSUE TITLE
Different Visualisation for Discussions

### ISSUE THREAD

**Issue by marcuspecht** [WELTEN/dojo-ibl#95]
Show all questions sorted by most recent at top in a list 
and collapse the replies (do not show the comments)

**Comment by Titogelo** [comment]
It has been implemented but there are some issues listed below:
- memory leaks in child views
- sorting by date
- switching between Question Activity type & Discussion Activity type has some problems with memory leaks as well.

**Comment by Titogelo** [comment]
Memory leaks solved.
Sorting by date solved.
      - In Questions most recent at the top
      - Discussion threads most recent comments at the bottom.
Switching issues solved.
- Reply to comments does not work.
